import { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Security & Data Protection | IntervueAI",
  description: "Learn how IntervueAI secures your resume data, limits database access, and shields user private session data.",
};

export default function SecurityPage() {
  return (
    <>
      <Navbar />
      <main className="container animate-fade-in" style={{ padding: "4rem 1.5rem", maxWidth: "800px" }}>
        <Link href="/" style={{ fontSize: "0.85rem", color: "var(--text-secondary)", display: "inline-flex", alignItems: "center", gap: "0.4rem", marginBottom: "1.5rem" }}>
          ← Back to Home
        </Link>
        <article className="glass-panel" style={{ padding: "3.5rem" }}>
          <h1 style={{ fontSize: "2.4rem", marginBottom: "0.5rem" }}>Security & Data Protection</h1>
          <p style={{ color: "var(--text-muted)", fontSize: "0.85rem", marginBottom: "2.5rem" }}>Last Updated: June 21, 2026</p>

          <section style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
            <div>
              <h2 style={{ fontSize: "1.4rem", marginBottom: "0.75rem", color: "var(--secondary)" }}>1. Encryption in Transit and at Rest</h2>
              <p style={{ color: "var(--text-secondary)", fontSize: "0.95rem", lineHeight: "1.7" }}>
                IntervueAI secures all network communications using Transport Layer Security (TLS 1.3). All database documents in Firestore and uploaded resume files in Firebase Storage are encrypted at rest using AES-256 keys managed by Google Cloud.
              </p>
            </div>

            <div>
              <h2 style={{ fontSize: "1.4rem", marginBottom: "0.75rem", color: "var(--secondary)" }}>2. Strict Access Boundaries</h2>
              <p style={{ color: "var(--text-secondary)", fontSize: "0.95rem", lineHeight: "1.7" }}>
                Our database infrastructure utilizes granular Firestore Security Rules and Storage Security Rules:
              </p>
              <ul style={{ paddingLeft: "1.25rem", marginTop: "0.5rem", color: "var(--text-secondary)", display: "flex", flexDirection: "column", gap: "0.5rem", fontSize: "0.95rem" }}>
                <li><b>Isolation</b>: Users can only read and write documents matching their verified `userId` generated by Firebase Authentication.</li>
                <li><b>Validation</b>: Content validation guarantees uploaded files are limited in size (Max 5MB) and type (restricted to `.pdf` and `.docx` only).</li>
                <li><b>Asynchronous Scoring</b>: Evaluation scores are calculated on protected Serverless environments, blocking clients from writing artificial scores directly.</li>
              </ul>
            </div>

            <div>
              <h2 style={{ fontSize: "1.4rem", marginBottom: "0.75rem", color: "var(--secondary)" }}>3. Safe AI Processing</h2>
              <p style={{ color: "var(--text-secondary)", fontSize: "0.95rem", lineHeight: "1.7" }}>
                When your resume is parsed or your mock replies are scored, data is transmitted to our backend AI engine via secure API channels. None of your personal data or response logs are submitted to public registries or utilized for training AI models.
              </p>
            </div>

            <div>
              <h2 style={{ fontSize: "1.4rem", marginBottom: "0.75rem", color: "var(--secondary)" }}>4. Vulnerability Disclosures</h2>
              <p style={{ color: "var(--text-secondary)", fontSize: "0.95rem", lineHeight: "1.7" }}>
                We actively monitor the platform for software vulnerabilities and dependency updates. If you discover a security vulnerability, please report it privately to our operations team. We are committed to addressing valid concerns within 72 hours.
              </p>
            </div>
          </section>
        </article>
      </main>
    </>
  );
}
